.TH "Enemy2" 3 "Tue Jan 10 2023" "Version 1" "Zuldesi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enemy2
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEnemy0\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnemy2\fP (int y, int x, char c, int mv)"
.br
.ti -1c
.RI "\fBEnemy2\fP ()"
.br
.ti -1c
.RI "void \fBmovement\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBEnemy0\fP
.in +1c
.ti -1c
.RI "\fBEnemy0\fP (int y, int x, char c, int mv)"
.br
.ti -1c
.RI "\fBEnemy0\fP ()"
.br
.ti -1c
.RI "virtual void \fBmovement\fP ()"
.br
.ti -1c
.RI "void \fBEnemyGoDown\fP ()"
.br
.ti -1c
.RI "int \fBgetx\fP () const"
.br
.ti -1c
.RI "int \fBgety\fP () const"
.br
.ti -1c
.RI "int \fBgetLife\fP () const"
.br
.ti -1c
.RI "int \fBgetSign\fP () const"
.br
.ti -1c
.RI "char \fBgetChar\fP () const"
.br
.ti -1c
.RI "void \fBsetSign\fP ()"
.br
.ti -1c
.RI "void \fBupdateCoordinates\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBsetLife\fP (int \fBlife\fP)"
.br
.ti -1c
.RI "void \fBinjury\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBEnemy0\fP
.in +1c
.ti -1c
.RI "int \fBsegno\fP {}"
.br
.ti -1c
.RI "int \fBxLoc\fP {}"
.br
.ti -1c
.RI "int \fByLoc\fP {}"
.br
.ti -1c
.RI "int \fBlife\fP {}"
.br
.ti -1c
.RI "char \fBcharacter\fP {}"
.br
.ti -1c
.RI "int \fBxpern\fP {}"
.br
.ti -1c
.RI "int \fBypern\fP {}"
.br
.ti -1c
.RI "int \fBcost\fP {}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Enemy2::Enemy2 (int y, int x, char c, int mv)"
Constructor with parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fIy\fP 
.br
\fIx\fP 
.br
\fIc\fP 
.br
\fImv\fP 
.RE
.PP

.SS "Enemy2::Enemy2 ()"
Default constructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Enemy2::movement ()\fC [override]\fP, \fC [virtual]\fP"
Change the movement direction\&. 
.PP
Reimplemented from \fBEnemy0\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zuldesi from the source code\&.
