.TH "listenemy3" 3 "Tue Jan 10 2023" "Version 1" "Zuldesi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listenemy3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Map\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBval\fP"
.br
.ti -1c
.RI "\fBEnemy3\fP \fBenemy\fP"
.br
.ti -1c
.RI "\fBlistenemy3\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
List of enemies type3\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Zuldesi from the source code\&.
