.TH "map_el" 3 "Tue Jan 10 2023" "Version 1" "Zuldesi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
map_el
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP {}"
.br
.ti -1c
.RI "\fBMap\fP \fBmap\fP"
.br
.ti -1c
.RI "\fBmap_el\fP * \fBnext\fP {}"
.br
.ti -1c
.RI "\fBmap_el\fP * \fBprev\fP {}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Zuldesi from the source code\&.
