.TH "md__documentation" 3 "Tue Jan 10 2023" "Version 1" "Zuldesi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__documentation \- Project roles 
.PP

.IP "\(bu" 2
LoscoX as Level designer
.IP "\(bu" 2
ardu2 as GUI designer
.IP "\(bu" 2
Davide as \fBGame\fP designer
.IP "\(bu" 2
Gabriel Preite as Checkpoint designer
.PP
.SH "Design points"
.PP
.SS "Level design"
.IP "\(bu" 2
Horizontal level
.IP "\(bu" 2
Infinity level
.IP "\(bu" 2
Rouge-lite level
.IP "\(bu" 2
Market level for each X meters on map
.IP "\(bu" 2
Market level in an other screen
.IP "\(bu" 2
\fBPlayer\fP must enters in the market level each time it appears
.IP "\(bu" 2
Cam dependency by player movement
.PP
.SS "Game Design"
.IP "\(bu" 2
One touch kill
.IP "\(bu" 2
Possibility of life or defense
.IP "\(bu" 2

.PP
.SS "GUI Design"
.IP "\(bu" 2
Different interface colors from the game
.PP
.SS "Checkpoint Design"
.IP "\(bu" 2

.PP

