.TH "platform" 3 "Tue Jan 10 2023" "Version 1" "Zuldesi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
platform
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Board\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBgraph\fP [len]"
.br
.ti -1c
.RI "int \fBxpos\fP [len]"
.br
.ti -1c
.RI "int \fBypos\fP [len]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for a platform\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Zuldesi from the source code\&.
