.TH "Powerup" 3 "Tue Jan 10 2023" "Version 1" "Zuldesi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Powerup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPowerup\fP (string \fBname\fP, string \fBdescription\fP, int \fBqnt\fP, int \fBprice\fP, int \fBdifficulty\fP)"
.br
.ti -1c
.RI "string \fBgetName\fP ()"
.br
.ti -1c
.RI "string \fBgetDescription\fP ()"
.br
.ti -1c
.RI "int \fBgetQnt\fP ()"
.br
.ti -1c
.RI "int \fBgetPrice\fP ()"
.br
.ti -1c
.RI "int \fBgetDifficulty\fP ()"
.br
.ti -1c
.RI "void \fBsetQnt\fP (int \fBqnt\fP)"
.br
.ti -1c
.RI "void \fBsetName\fP (string \fBname\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBdescription\fP"
.br
.ti -1c
.RI "int \fBqnt\fP"
.br
.ti -1c
.RI "int \fBprice\fP"
.br
.ti -1c
.RI "int \fBdifficulty\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string Powerup::description"
Description\&. 
.SS "int Powerup::difficulty"
Measures how much the difficulty should increase when bought\&. 
.SS "string Powerup::name"
Power-up identifier\&. 
.SS "int Powerup::price"
Price\&. 
.SS "int Powerup::qnt"
Quantity of power-up\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Zuldesi from the source code\&.
