.TH "segment_el" 3 "Tue Jan 10 2023" "Version 1" "Zuldesi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
segment_el
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Map\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "\fBSegment\fP \fBseg\fP"
.br
.ti -1c
.RI "\fBsegment_el\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Element of segment list\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Zuldesi from the source code\&.
