.TH "Segment" 3 "Tue Jan 10 2023" "Version 1" "Zuldesi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Segment
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSegment\fP (string path)"
.br
.ti -1c
.RI "string * \fBgetMatrix\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "string * Segment::getMatrix ()"

.PP
\fBReturns\fP
.RS 4
Matrix segments\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Zuldesi from the source code\&.
